### ISSUE TITLE
Type Error : Super.__init__ takes atlast one argument (0 given)

### ISSUE THREAD

**Issue by HRKagdi** [YangDi666/2s-AGCN-For-Daily-Living#1]
![issue](https://user-images.githubusercontent.com/53858937/96668451-ce1de100-1378-11eb-84cf-5848a24bd0fe.png)
  

I am running main.py for smarthome -cross-subject/train_joint.yaml
What should i do to resolve this error?

**Comment by YangDi666** [comment]
I suggest you to use Python3, for Python2, it should be:
super( GradualWarmupScheduler, self).__init__(optimizer)

**Comment by HRKagdi** [comment]
Thank You very much Sir.It is working.

**Comment by HRKagdi** [comment]
Respected Sir,
We are working upon the model that you have built for ToyotaSmarthome
Dataset.We got top-5 accuracy of 92%for train_joint and the training is
currently being done for train_bone configs.It is under process.

What other things can we do to improve the accuracy?Can you please suggest
us something so as to improve the model.

Thanking You .
Yours Sincerely
Hussain Kagdi
