### ISSUE TITLE
why do you set # joint to 15 since in Toyota smarthome dataset # joints is 13?

### ISSUE THREAD

**Issue by monacv** [YangDi666/2s-AGCN-For-Daily-Living#4]
Thanks a lot for providing the Python file for graph of smarthome dataset. However, # joints in the dataset I downloaded is 13 while you set it to 15.

Could you please guide me how to change line 8 and 9 below to reflect my toyota smarthome dataset which only has 13 joints?

![Screenshot from 2021-02-17 00-03-22](https://user-images.githubusercontent.com/76495162/108158969-0e396a00-70b4-11eb-8809-c3f48d96535e.png)

**Comment by cyoungx** [comment]
I also want to know the reason.
